/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.zw255.battleship.server;

import edu.duke.zw255.battleship.shared.*;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.io.IOException;
import java.net.ServerSocket;
import java.util.concurrent.ThreadPoolExecutor;

import org.checkerframework.checker.units.qual.s;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;



class ServerTest {
  @Test
  public void test_joinfail() throws InterruptedException, IOException, ClassNotFoundException {


    Thread th = new Thread() {
      @Override()
      public void run() {
        try {
          String[] s = new String[1];
          
          Server.main(s);
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    };
    th.start();
    Thread.sleep(100); // a bit of hack
    Messenger client1 = new Messenger("127.0.0.1", 12345);
    //assertEquals(0, Server.roomMap.size());
    client1.send("join");
    client1.send("b");
    int flag=(int)client1.recv();
    assertEquals(Flag.errorFlag, flag);
    client1.closeMessenger();
  }


  @Test
  public void test_joinSuccess() throws InterruptedException, IOException, ClassNotFoundException {


    Thread th = new Thread() {
      @Override()
      public void run() {
        try {
          String[] s = new String[1];
          ServerSocket serverSocket= new ServerSocket(12346);
          Server.roomMap.put("c",new RoomHandler("c", serverSocket));
          Server.roomContainer=1;
          Server.main(s);
        } catch (Exception e) {
        }
      }
    };
    th.start();
    Thread.sleep(100); // a bit of hack
    Messenger client1 = new Messenger("127.0.0.1", 12345);

    client1.send("join");
    client1.send("c");
    int flag2=(int)client1.recv();
    assertEquals(Flag.correctFlag, flag2);
    
    client1.closeMessenger();
  }

  @Test
  public void test_init() throws InterruptedException, IOException, ClassNotFoundException {

    Thread th = new Thread() {
      @Override()
      public void run() {
        try {
          String[] s = new String[1];
          Server.main(s);
        } catch (Exception e) {
        }
      }
    };
    th.start();
    Thread.sleep(100); // a bit of hack
    Messenger client1 = new Messenger("127.0.0.1", 12345);
    assertEquals(0, Server.roomMap.size());
    client1.send("init");
    client1.send("a");

    client1.closeMessenger();
  }
}
