/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.zw255.battleship.client;


public class Client {
    public static void main(String[] args) {
        //LinkedList tokens=new LinkedList();
        //System.out.println(tokens.size());
    }
}
