/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.zw255.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
  final TextPlayer player1;
  final TextPlayer player2;
  
  public App(Board<Character> Board1,Board<Character> Board2, BufferedReader inputSource, PrintStream out) {
    V1ShipFactory shipFactory=new V1ShipFactory();
    this.player1=new TextPlayer("A",Board1, inputSource, out, shipFactory);
    this.player2=new TextPlayer("B",Board2, inputSource, out, shipFactory);
  }

  public void doPlacementPhase() throws IOException{
    player1.doPlacementPhase();
    player2.doPlacementPhase();
  }

  public void doAttackingPhase() throws IOException{
    while(true){
    player1.playOneTurn(player2.theBoard,player2.view);
    player2.playOneTurn(player1.theBoard, player1.view);
    }
  }

  public static void main(String[] args) throws IOException {
   Board b1=new BattleShipBoard<>(10, 20,'X');
   Board b2=new BattleShipBoard<>(10, 20,'X');
   
   App app=new App(b1,b2,new BufferedReader((new  InputStreamReader(System.in))),System.out);
   app.doPlacementPhase();
   app.doAttackingPhase();
  }
}
